# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telasinaisvitais.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!
import sqlite3

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SinaisVitais(object):
    def setupUi(self, SinaisVitais):
        SinaisVitais.setObjectName("SinaisVitais")
        SinaisVitais.resize(684, 518)
        self.label = QtWidgets.QLabel(SinaisVitais)
        self.label.setGeometry(QtCore.QRect(10, 170, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(SinaisVitais)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        SinaisVitais.setModal(True)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.camPesqPacVitais = QtWidgets.QLineEdit(SinaisVitais)
        self.camPesqPacVitais.setGeometry(QtCore.QRect(10, 30, 311, 21))
        self.camPesqPacVitais.setObjectName("camPesqPacVitais")
        self.btnPesqVitais = QtWidgets.QPushButton(SinaisVitais)
        self.btnPesqVitais.setGeometry(QtCore.QRect(340, 20, 91, 31))
        self.btnPesqVitais.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../imagens/lupa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPesqVitais.setIcon(icon)
        self.btnPesqVitais.setObjectName("btnPesqVitais")
        self.PacienteVatais = QtWidgets.QTableWidget(SinaisVitais)
        self.PacienteVatais.setGeometry(QtCore.QRect(10, 60, 661, 91))
        self.PacienteVatais.setObjectName("PacienteVatais")
        self.PacienteVatais.setColumnCount(8)
        self.PacienteVatais.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.PacienteVatais.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.PacienteVatais.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.PacienteVatais.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.PacienteVatais.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.PacienteVatais.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.PacienteVatais.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.PacienteVatais.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.PacienteVatais.setHorizontalHeaderItem(7, item)
        self.camPresArterial = QtWidgets.QLineEdit(SinaisVitais)
        self.camPresArterial.setGeometry(QtCore.QRect(10, 190, 151, 21))
        self.camPresArterial.setObjectName("camPresArterial")
        self.label_3 = QtWidgets.QLabel(SinaisVitais)
        self.label_3.setGeometry(QtCore.QRect(10, 220, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.camTemp = QtWidgets.QLineEdit(SinaisVitais)
        self.camTemp.setGeometry(QtCore.QRect(10, 250, 151, 21))
        self.camTemp.setObjectName("camTemp")
        self.label_4 = QtWidgets.QLabel(SinaisVitais)
        self.label_4.setGeometry(QtCore.QRect(10, 280, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.camCard = QtWidgets.QLineEdit(SinaisVitais)
        self.camCard.setGeometry(QtCore.QRect(10, 310, 151, 21))
        self.camCard.setObjectName("camCard")
        self.label_5 = QtWidgets.QLabel(SinaisVitais)
        self.label_5.setGeometry(QtCore.QRect(10, 340, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.camResp = QtWidgets.QLineEdit(SinaisVitais)
        self.camResp.setGeometry(QtCore.QRect(10, 370, 151, 20))
        self.camResp.setObjectName("camResp")
        self.label_6 = QtWidgets.QLabel(SinaisVitais)
        self.label_6.setGeometry(QtCore.QRect(10, 400, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.camGlic = QtWidgets.QLineEdit(SinaisVitais)
        self.camGlic.setGeometry(QtCore.QRect(10, 430, 151, 20))
        self.camGlic.setObjectName("camGlic")
        self.scrollArea = QtWidgets.QScrollArea(SinaisVitais)
        self.scrollArea.setGeometry(QtCore.QRect(270, 460, 401, 51))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 399, 49))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.btnCancelarVitais = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnCancelarVitais.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../imagens/cancelar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancelarVitais.setIcon(icon1)
        self.btnCancelarVitais.setObjectName("btnCancelarVitais")
        self.gridLayout.addWidget(self.btnCancelarVitais, 0, 1, 1, 1)
        self.btnSalvarVitais = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnSalvarVitais.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../imagens/ok.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSalvarVitais.setIcon(icon2)
        self.btnSalvarVitais.setObjectName("btnSalvarVitais")
        self.gridLayout.addWidget(self.btnSalvarVitais, 0, 2, 1, 1)
        self.btnEditar = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnEditar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../imagens/editar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEditar.setIcon(icon3)
        self.btnEditar.setObjectName("btnEditar")
        self.gridLayout.addWidget(self.btnEditar, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_7 = QtWidgets.QLabel(SinaisVitais)
        self.label_7.setGeometry(QtCore.QRect(460, 170, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.line = QtWidgets.QFrame(SinaisVitais)
        self.line.setGeometry(QtCore.QRect(250, 170, 16, 341))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_8 = QtWidgets.QLabel(SinaisVitais)
        self.label_8.setGeometry(QtCore.QRect(270, 220, 47, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(SinaisVitais)
        self.label_9.setGeometry(QtCore.QRect(270, 250, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(SinaisVitais)
        self.label_10.setGeometry(QtCore.QRect(270, 270, 111, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(SinaisVitais)
        self.label_11.setGeometry(QtCore.QRect(270, 300, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(SinaisVitais)
        self.label_12.setGeometry(QtCore.QRect(270, 330, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(SinaisVitais)
        self.label_13.setGeometry(QtCore.QRect(270, 350, 47, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.lblNomePaciente = QtWidgets.QLabel(SinaisVitais)
        self.lblNomePaciente.setGeometry(QtCore.QRect(315, 220, 281, 21))
        self.lblNomePaciente.setText("")
        self.lblNomePaciente.setObjectName("lblNomePaciente")
        self.lblLeitoPac = QtWidgets.QLabel(SinaisVitais)
        self.lblLeitoPac.setGeometry(QtCore.QRect(307, 249, 81, 16))
        self.lblLeitoPac.setText("")
        self.lblLeitoPac.setObjectName("lblLeitoPac")
        self.lblPres = QtWidgets.QLabel(SinaisVitais)
        self.lblPres.setGeometry(QtCore.QRect(383, 273, 91, 16))
        self.lblPres.setText("")
        self.lblPres.setObjectName("lblPres")
        self.lblTemp = QtWidgets.QLabel(SinaisVitais)
        self.lblTemp.setGeometry(QtCore.QRect(360, 303, 121, 16))
        self.lblTemp.setText("")
        self.lblTemp.setObjectName("lblTemp")
        self.lblFA = QtWidgets.QLabel(SinaisVitais)
        self.lblFA.setGeometry(QtCore.QRect(300, 326, 81, 20))
        self.lblFA.setText("")
        self.lblFA.setObjectName("lblFA")
        self.lblFR = QtWidgets.QLabel(SinaisVitais)
        self.lblFR.setGeometry(QtCore.QRect(300, 350, 61, 21))
        self.lblFR.setText("")
        self.lblFR.setObjectName("lblFR")

        self.retranslateUi(SinaisVitais)
        QtCore.QMetaObject.connectSlotsByName(SinaisVitais)

        self.btnCancelarVitais.clicked.connect(SinaisVitais.close)
        self.btnPesqVitais.clicked.connect(self.Atualizar)

    def Atualizar(self):
        self.connection = sqlite3.connect('Paciente.db')
        self.query = "SELECT idInter, nome, leito, PA, temperatura, FA, FR, glicemia from internacao"
        self.result = self.connection.execute(self.query)
        self.PacienteVatais.setRowCount(0)
        for row_number, row_data in enumerate(self.result):
            self.PacienteVatais.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.PacienteVatais.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))
                self.lblNomePaciente.setText(str(row_data[1]))
                self.lblLeitoPac.setText(str(row_data[2]))
                self.lblPres.setText(str(row_data[3]))
                self.lblTemp.setText(str(row_data[4]))
                self.lblFA.setText(str(row_data[5]))
                self.lblFR.setText(str(row_data[6]))

                #campos para editar
                self.camPresArterial.setText(str(row_data[3]))
                self.camTemp.setText(str(row_data[4]))
                self.camCard.setText(str(row_data[5]))
                self.camResp.setText(str(row_data[6]))
                self.camGlic.setText(str(row_data[7]))

        self.connection.close()

    def retranslateUi(self, SinaisVitais):
        _translate = QtCore.QCoreApplication.translate
        SinaisVitais.setWindowTitle(_translate("SinaisVitais", "Sinais Vitais"))
        self.label.setText(_translate("SinaisVitais", "Pressão Arterial:"))
        self.label_2.setText(_translate("SinaisVitais", "Pesquisa Paciente:"))
        self.btnPesqVitais.setText(_translate("SinaisVitais", "Pesquisar"))
        item = self.PacienteVatais.horizontalHeaderItem(0)
        item.setText(_translate("SinaisVitais", "ID"))
        item = self.PacienteVatais.horizontalHeaderItem(1)
        item.setText(_translate("SinaisVitais", "Nome"))
        item = self.PacienteVatais.horizontalHeaderItem(2)
        item.setText(_translate("SinaisVitais", "Leito"))
        item = self.PacienteVatais.horizontalHeaderItem(3)
        item.setText(_translate("SinaisVitais", "Pressão Arterial"))
        item = self.PacienteVatais.horizontalHeaderItem(4)
        item.setText(_translate("SinaisVitais", "Temperatura"))
        item = self.PacienteVatais.horizontalHeaderItem(5)
        item.setText(_translate("SinaisVitais", "Frequencia Cardiaca"))
        item = self.PacienteVatais.horizontalHeaderItem(6)
        item.setText(_translate("SinaisVitais", "Frequencia Respiratoria"))
        item = self.PacienteVatais.horizontalHeaderItem(7)
        item.setText(_translate("SinaisVitais", "Glicemia"))
        self.label_3.setText(_translate("SinaisVitais", "Temperatura:"))
        self.label_4.setText(_translate("SinaisVitais", "Frequência Cardiaca:"))
        self.label_5.setText(_translate("SinaisVitais", "Frequência Respiratoria:"))
        self.label_6.setText(_translate("SinaisVitais", "Glicemia:"))
        self.btnCancelarVitais.setText(_translate("SinaisVitais", "Cancelar"))
        self.btnSalvarVitais.setText(_translate("SinaisVitais", "Salvar"))
        self.btnEditar.setText(_translate("SinaisVitais", "Editar"))
        self.label_7.setText(_translate("SinaisVitais", "Paciente"))
        self.label_8.setText(_translate("SinaisVitais", "Nome:"))
        self.label_9.setText(_translate("SinaisVitais", "Leito:"))
        self.label_10.setText(_translate("SinaisVitais", "Pressão Arterial:"))
        self.label_11.setText(_translate("SinaisVitais", "Temperatura:"))
        self.label_12.setText(_translate("SinaisVitais", "F.A:"))
        self.label_13.setText(_translate("SinaisVitais", "F.R:"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SinaisVitais = QtWidgets.QDialog()
    ui = Ui_SinaisVitais()
    ui.setupUi(SinaisVitais)
    SinaisVitais.show()
    sys.exit(app.exec_())
