# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telamedico.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!
import sqlite3

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_TelaMedico(object):
    def setupUi(self, TelaMedico):
        TelaMedico.setObjectName("TelaMedico")
        TelaMedico.setFixedSize(707, 626)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../imagens/medico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TelaMedico.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(TelaMedico)
        self.label.setGeometry(QtCore.QRect(10, 0, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        TelaMedico.setModal(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(TelaMedico)
        self.label_2.setGeometry(QtCore.QRect(10, 180, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(TelaMedico)
        self.label_3.setGeometry(QtCore.QRect(470, 180, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(TelaMedico)
        self.label_4.setGeometry(QtCore.QRect(140, 180, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(TelaMedico)
        self.label_5.setGeometry(QtCore.QRect(590, 180, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(TelaMedico)
        self.label_6.setGeometry(QtCore.QRect(10, 210, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(TelaMedico)
        self.label_7.setGeometry(QtCore.QRect(70, 210, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.btnProximoPaciente = QtWidgets.QPushButton(TelaMedico)
        self.btnProximoPaciente.setGeometry(QtCore.QRect(550, 140, 141, 31))
        self.btnProximoPaciente.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../imagens/proximo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnProximoPaciente.setIcon(icon1)
        self.btnProximoPaciente.setObjectName("btnProximoPaciente")
        self.textEdit = QtWidgets.QTextEdit(TelaMedico)
        self.textEdit.setGeometry(QtCore.QRect(10, 270, 691, 101))
        self.textEdit.setObjectName("textEdit")
        self.label_8 = QtWidgets.QLabel(TelaMedico)
        self.label_8.setGeometry(QtCore.QRect(10, 250, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.line = QtWidgets.QFrame(TelaMedico)
        self.line.setGeometry(QtCore.QRect(0, 230, 721, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_9 = QtWidgets.QLabel(TelaMedico)
        self.label_9.setGeometry(QtCore.QRect(10, 400, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.textEdit_2 = QtWidgets.QTextEdit(TelaMedico)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 420, 691, 91))
        self.textEdit_2.setObjectName("textEdit_2")
        self.line_2 = QtWidgets.QFrame(TelaMedico)
        self.line_2.setGeometry(QtCore.QRect(0, 380, 701, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.groupBox = QtWidgets.QGroupBox(TelaMedico)
        self.groupBox.setGeometry(QtCore.QRect(10, 530, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 20, 51, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(70, 20, 51, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.groupBox_2 = QtWidgets.QGroupBox(TelaMedico)
        self.groupBox_2.setGeometry(QtCore.QRect(160, 530, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 20, 61, 17))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_4.setGeometry(QtCore.QRect(70, 20, 51, 17))
        self.radioButton_4.setObjectName("radioButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(TelaMedico)
        self.pushButton_3.setGeometry(QtCore.QRect(500, 580, 191, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.scrollArea = QtWidgets.QScrollArea(TelaMedico)
        self.scrollArea.setGeometry(QtCore.QRect(400, 520, 301, 51))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 299, 49))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../imagens/editar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../imagens/ok.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tableWidget = QtWidgets.QTableWidget(TelaMedico)
        self.tableWidget.setGeometry(QtCore.QRect(5, 30, 691, 101))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)

        self.retranslateUi(TelaMedico)
        QtCore.QMetaObject.connectSlotsByName(TelaMedico)

        # Deixa campo Observação Paciente desabilitado
        desabilitado = False if self.textEdit.isEnabled() else True
        self.textEdit.setEnabled(desabilitado)

        self.btnProximoPaciente.clicked.connect(self.Nova)
        self.pushButton.clicked.connect(self.Salvar)



    def Nova(self):
            connection = sqlite3.connect('Paciente.db')
            query = "SELECT nome, data, idade, cpf, rg, uf, obsTri, status FROM paciente, enfermeiro"
            result = connection.execute(query)
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))
                    self.textEdit.setText(str(row_data[6]))
                    self.label_4.setText(str(row_data[0]))
                    self.label_7.setText(str(row_data[7]))


            connection.close()

    def Salvar(self):
        obsMedidico = ""

        obsMedico = self.textEdit_2.toPlainText()


        try:
            self.conn = sqlite3.connect("Paciente.db")
            self.c = self.conn.cursor()
            self.c.execute("UPDATE paciente set evomedica =? ",(obsMedico))
            self.conn.commit()
            self.c.close()
            self.conn.close()
            QMessageBox.information(QMessageBox(), 'Salvo com sucesso', 'Obs salvo com sucesso')
        except Exception:
            QMessageBox.warning(QMessageBox(), 'Erro ao salvar', 'Confira todos os campos')


    def retranslateUi(self, TelaMedico):
        _translate = QtCore.QCoreApplication.translate
        TelaMedico.setWindowTitle(_translate("TelaMedico", "Atendimento Medico"))
        self.label.setText(_translate("TelaMedico", "Pacientes em espera:"))
        self.label_2.setText(_translate("TelaMedico", "Nome do Paciente:"))
        self.label_3.setText(_translate("TelaMedico", "Hora de entrada:"))
        self.label_6.setText(_translate("TelaMedico", "Status:"))
        self.btnProximoPaciente.setText(_translate("TelaMedico", "Proximo"))
        self.label_8.setText(_translate("TelaMedico", "Observação da Triagem:"))
        self.label_9.setText(_translate("TelaMedico", "Diagnostico Medico:"))
        self.groupBox.setTitle(_translate("TelaMedico", "Medicamento?"))
        self.radioButton.setText(_translate("TelaMedico", "Sim"))
        self.radioButton_2.setText(_translate("TelaMedico", "Não"))
        self.groupBox_2.setTitle(_translate("TelaMedico", "Internação?"))
        self.radioButton_3.setText(_translate("TelaMedico", "Sim"))
        self.radioButton_4.setText(_translate("TelaMedico", "Não"))
        self.pushButton_3.setText(_translate("TelaMedico", "Finalizar Atendimento"))
        self.pushButton_2.setText(_translate("TelaMedico", "Editar"))
        self.pushButton.setText(_translate("TelaMedico", "Salvar"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TelaMedico", "Nome"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TelaMedico", "nascimento"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TelaMedico", "idade"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("TelaMedico", "cpf"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("TelaMedico", "rg"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("TelaMedico", "uf"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("TelaMedico", "Obs Enfermeiro"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaMedico = QtWidgets.QDialog()
    ui = Ui_TelaMedico()
    ui.setupUi(TelaMedico)
    TelaMedico.show()
    sys.exit(app.exec_())
