# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaatendimento.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!
import sqlite3
from datetime import datetime

import pycep_correios
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTime
from PyQt5.QtWidgets import QComboBox, QVBoxLayout, QMessageBox, QWidget, QLabel, QLineEdit, QPushButton, QRadioButton


class Ui_TelaAtendimento(object):
    def setupUi(self, TelaAtendimento):
        TelaAtendimento.setObjectName("TelaAtendimento")
        TelaAtendimento.setFixedSize(568, 666)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../imagens/atendimento.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TelaAtendimento.setWindowIcon(icon)
        self.label_19 = QtWidgets.QLabel(TelaAtendimento)
        self.label_19.setGeometry(QtCore.QRect(20, 450, 150, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        TelaAtendimento.setModal(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_9 = QtWidgets.QLabel(TelaAtendimento)
        self.label_9.setGeometry(QtCore.QRect(20, 270, 44, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.BairroCliente = QtWidgets.QLineEdit(TelaAtendimento)
        self.BairroCliente.setGeometry(QtCore.QRect(20, 290, 171, 20))
        self.BairroCliente.setObjectName("BairroCliente")
        self.label_15 = QtWidgets.QLabel(TelaAtendimento)
        self.label_15.setGeometry(QtCore.QRect(420, 350, 36, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label = QtWidgets.QLabel(TelaAtendimento)
        self.label.setGeometry(QtCore.QRect(170, 80, 22, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Especialista = QtWidgets.QComboBox(TelaAtendimento)
        self.Especialista.setGeometry(QtCore.QRect(20, 420, 201, 20))
        self.Especialista.setObjectName("Especialista")
        self.line_3 = QtWidgets.QFrame(TelaAtendimento)
        self.line_3.setGeometry(QtCore.QRect(-3, 310, 561, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_3 = QtWidgets.QLabel(TelaAtendimento)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 79, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.dtaNascimento = QtWidgets.QLineEdit(TelaAtendimento)
        self.dtaNascimento.setGeometry(QtCore.QRect(380, 50, 91, 20))
        self.dtaNascimento.setInputMethodHints(QtCore.Qt.ImhDate)
        self.dtaNascimento.setObjectName("dtaNascimento")
        self.label_11 = QtWidgets.QLabel(TelaAtendimento)
        self.label_11.setGeometry(QtCore.QRect(200, 270, 92, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.lblNomeCompleto = QtWidgets.QLabel(TelaAtendimento)
        self.lblNomeCompleto.setGeometry(QtCore.QRect(20, 30, 104, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblNomeCompleto.setFont(font)
        self.lblNomeCompleto.setObjectName("lblNomeCompleto")
        self.FormAtendimento = QtWidgets.QComboBox(TelaAtendimento)
        self.FormAtendimento.setGeometry(QtCore.QRect(220, 421, 201, 20))
        self.FormAtendimento.setObjectName("FormAtendimento")
        self.label_16 = QtWidgets.QLabel(TelaAtendimento)
        self.label_16.setGeometry(QtCore.QRect(20, 400, 80, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.line_2 = QtWidgets.QFrame(TelaAtendimento)
        self.line_2.setGeometry(QtCore.QRect(0, 20, 571, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.PassaporteCliente = QtWidgets.QLineEdit(TelaAtendimento)
        self.PassaporteCliente.setGeometry(QtCore.QRect(20, 170, 133, 20))
        self.PassaporteCliente.setObjectName("PassaporteCliente")
        self.label_13 = QtWidgets.QLabel(TelaAtendimento)
        self.label_13.setGeometry(QtCore.QRect(20, 350, 139, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.RGCliente = QtWidgets.QLineEdit(TelaAtendimento)
        self.RGCliente.setGeometry(QtCore.QRect(170, 100, 71, 20))
        self.RGCliente.setObjectName("RGCliente")
        self.hrEntrada = QtWidgets.QLineEdit(TelaAtendimento)
        self.hrEntrada.setGeometry(QtCore.QRect(420, 370, 121, 20))
        self.hrEntrada.setObjectName("hrEntrada")
        self.ValorAtendimento = QtWidgets.QLineEdit(TelaAtendimento)
        self.ValorAtendimento.setGeometry(QtCore.QRect(440, 420, 101, 20))
        self.ValorAtendimento.setObjectName("ValorAtendimento")
        self.CPFProprio = QtWidgets.QCheckBox(TelaAtendimento)
        self.CPFProprio.setGeometry(QtCore.QRect(20, 120, 101, 17))
        self.CPFProprio.setObjectName("CPFProprio")
        self.lblNascimento = QtWidgets.QLabel(TelaAtendimento)
        self.lblNascimento.setGeometry(QtCore.QRect(380, 30, 79, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblNascimento.setFont(font)
        self.lblNascimento.setInputMethodHints(QtCore.Qt.ImhSensitiveData)
        self.lblNascimento.setObjectName("lblNascimento")
        self.RGProprio = QtWidgets.QCheckBox(TelaAtendimento)
        self.RGProprio.setGeometry(QtCore.QRect(170, 120, 71, 17))
        self.RGProprio.setObjectName("RGProprio")
        self.label_17 = QtWidgets.QLabel(TelaAtendimento)
        self.label_17.setGeometry(QtCore.QRect(230, 400, 152, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_4 = QtWidgets.QLabel(TelaAtendimento)
        self.label_4.setGeometry(QtCore.QRect(15, 9, 138, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.groupBox_2 = QtWidgets.QGroupBox(TelaAtendimento)
        self.groupBox_2.setGeometry(QtCore.QRect(170, 150, 131, 42))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(70, 20, 51, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(10, 20, 51, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.label_10 = QtWidgets.QLabel(TelaAtendimento)
        self.label_10.setGeometry(QtCore.QRect(480, 270, 49, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_7 = QtWidgets.QLabel(TelaAtendimento)
        self.label_7.setGeometry(QtCore.QRect(130, 220, 65, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(TelaAtendimento)
        self.label_8.setGeometry(QtCore.QRect(480, 220, 20, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lblIdade = QtWidgets.QLabel(TelaAtendimento)
        self.lblIdade.setGeometry(QtCore.QRect(490, 30, 42, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblIdade.setFont(font)
        self.lblIdade.setObjectName("lblIdade")
        self.OBSCliente = QtWidgets.QTextEdit(TelaAtendimento)
        self.OBSCliente.setGeometry(QtCore.QRect(20, 470, 531, 127))
        self.OBSCliente.setObjectName("OBSCliente")
        self.CEPCliente = QtWidgets.QLineEdit(TelaAtendimento)
        self.CEPCliente.setGeometry(QtCore.QRect(20, 240, 101, 20))
        self.CEPCliente.setObjectName("CEPCliente")
        self.CamNomeCompleto = QtWidgets.QLineEdit(TelaAtendimento)
        self.CamNomeCompleto.setGeometry(QtCore.QRect(20, 50, 351, 20))
        self.CamNomeCompleto.setObjectName("CamNomeCompleto")
        self.NomeConvenio = QtWidgets.QComboBox(TelaAtendimento)
        self.NomeConvenio.setGeometry(QtCore.QRect(220, 370, 181, 20))
        self.NomeConvenio.setObjectName("NomeConvenio")
        self.label_5 = QtWidgets.QLabel(TelaAtendimento)
        self.label_5.setGeometry(QtCore.QRect(20, 200, 163, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(TelaAtendimento)
        self.label_6.setGeometry(QtCore.QRect(20, 220, 28, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.ComboAtendimento = QtWidgets.QComboBox(TelaAtendimento)
        self.ComboAtendimento.setGeometry(QtCore.QRect(20, 370, 201, 20))
        self.ComboAtendimento.setObjectName("ComboAtendimento")
        self.label_12 = QtWidgets.QLabel(TelaAtendimento)
        self.label_12.setGeometry(QtCore.QRect(20, 320, 172, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.line = QtWidgets.QFrame(TelaAtendimento)
        self.line.setGeometry(QtCore.QRect(0, 190, 571, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_18 = QtWidgets.QLabel(TelaAtendimento)
        self.label_18.setGeometry(QtCore.QRect(440, 400, 39, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.NumeroCasa = QtWidgets.QLineEdit(TelaAtendimento)
        self.NumeroCasa.setGeometry(QtCore.QRect(480, 240, 60, 20))
        self.NumeroCasa.setObjectName("NumeroCasa")
        self.lblCPF = QtWidgets.QLabel(TelaAtendimento)
        self.lblCPF.setGeometry(QtCore.QRect(20, 80, 27, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblCPF.setFont(font)
        self.lblCPF.setObjectName("lblCPF")
        self.CPFCliente = QtWidgets.QLineEdit(TelaAtendimento)
        self.CPFCliente.setGeometry(QtCore.QRect(20, 100, 133, 20))
        self.CPFCliente.setObjectName("CPFCliente")
        self.IdadeCliente = QtWidgets.QLineEdit(TelaAtendimento)
        self.IdadeCliente.setGeometry(QtCore.QRect(490, 50, 54, 20))
        self.IdadeCliente.setObjectName("IdadeCliente")
        self.label_2 = QtWidgets.QLabel(TelaAtendimento)
        self.label_2.setGeometry(QtCore.QRect(250, 80, 19, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.ENDClinete = QtWidgets.QLineEdit(TelaAtendimento)
        self.ENDClinete.setGeometry(QtCore.QRect(130, 240, 321, 20))
        self.ENDClinete.setObjectName("ENDClinete")
        self.CompCliente = QtWidgets.QLineEdit(TelaAtendimento)
        self.CompCliente.setGeometry(QtCore.QRect(200, 290, 271, 20))
        self.CompCliente.setObjectName("CompCliente")
        self.label_14 = QtWidgets.QLabel(TelaAtendimento)
        self.label_14.setGeometry(QtCore.QRect(230, 350, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.UFExpedicao = QtWidgets.QComboBox(TelaAtendimento)
        self.UFExpedicao.setGeometry(QtCore.QRect(250, 100, 61, 25))
        self.UFExpedicao.setObjectName("UFExpedicao")
        self.groupBox = QtWidgets.QGroupBox(TelaAtendimento)
        self.groupBox.setGeometry(QtCore.QRect(320, 80, 221, 113))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.label_20.setObjectName("label_20")
        self.CampEmail = QtWidgets.QLineEdit(self.groupBox)
        self.CampEmail.setGeometry(QtCore.QRect(10, 40, 201, 20))
        self.CampEmail.setInputMethodHints(QtCore.Qt.ImhNone)
        self.CampEmail.setObjectName("CampEmail")
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        self.label_21.setGeometry(QtCore.QRect(10, 60, 47, 13))
        self.label_21.setObjectName("label_21")
        self.CampCelular = QtWidgets.QLineEdit(self.groupBox)
        self.CampCelular.setGeometry(QtCore.QRect(10, 80, 141, 20))
        self.CampCelular.setObjectName("CampCelular")
        self.estadoCliente = QtWidgets.QComboBox(TelaAtendimento)
        self.estadoCliente.setGeometry(QtCore.QRect(480, 290, 69, 22))
        self.estadoCliente.setObjectName("estadoCliente")
        self.scrollArea = QtWidgets.QScrollArea(TelaAtendimento)
        self.scrollArea.setGeometry(QtCore.QRect(200, 600, 351, 51))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 349, 49))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.btnCancelar = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnCancelar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../imagens/cancelar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancelar.setIcon(icon1)
        self.btnCancelar.setObjectName("btnCancelar")
        self.gridLayout.addWidget(self.btnCancelar, 0, 0, 1, 1)
        self.btnLimpar = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnLimpar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../imagens/lixeira.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLimpar.setIcon(icon2)
        self.btnLimpar.setObjectName("btnLimpar")
        self.gridLayout.addWidget(self.btnLimpar, 0, 1, 1, 1)
        self.btnSalvar = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnSalvar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../imagens/ok.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSalvar.setIcon(icon3)
        self.btnSalvar.setObjectName("btnSalvar")
        self.gridLayout.addWidget(self.btnSalvar, 0, 2, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.btnCancelar.clicked.connect(TelaAtendimento.close)

        self.btnLimpar.clicked.connect(self.Clear)
        self.btnSalvar.clicked.connect(self.Salvar)

        self.retranslateUi(TelaAtendimento)
        QtCore.QMetaObject.connectSlotsByName(TelaAtendimento)

        #Valor do atendimento fixo
        self.ValorAtendimento.setText("125,50")

        # Desabilitar valor
        desabilitado = False if self.ValorAtendimento.isEnabled() else True
        self.ValorAtendimento.setEnabled(desabilitado)






        #Data
        #self.btnSalvar.clicked.connect(self.Data)
        time = QTime.currentTime()
        text = time.toString('hh:mm:ss')
        self.hrEntrada.setText(text)


        #Desabilitar hora
        desabilitado = False if self.hrEntrada.isEnabled() else True
        self.hrEntrada.setEnabled(desabilitado)


       # Combo Expediçao

        self.UFExpedicao.addItem("UF")
        self.UFExpedicao.addItem("AC")
        self.UFExpedicao.addItem("AL")
        self.UFExpedicao.addItem("AM")
        self.UFExpedicao.addItem("AP")
        self.UFExpedicao.addItem("BA")
        self.UFExpedicao.addItem("CE")
        self.UFExpedicao.addItem("DF")
        self.UFExpedicao.addItem("ES")
        self.UFExpedicao.addItem("GO")
        self.UFExpedicao.addItem("MA")
        self.UFExpedicao.addItem("MG")
        self.UFExpedicao.addItem("MS")
        self.UFExpedicao.addItem("MT")
        self.UFExpedicao.addItem("PA")
        self.UFExpedicao.addItem("PB")
        self.UFExpedicao.addItem("PE")
        self.UFExpedicao.addItem("PI")
        self.UFExpedicao.addItem("PR")
        self.UFExpedicao.addItem("RJ")
        self.UFExpedicao.addItem("RN")
        self.UFExpedicao.addItem("RO")
        self.UFExpedicao.addItem("RR")
        self.UFExpedicao.addItem("RS")
        self.UFExpedicao.addItem("SC")
        self.UFExpedicao.addItem("SE")
        self.UFExpedicao.addItem("SP")
        self.UFExpedicao.addItem("TO")




        #Combo Estado do cliente
        self.estadoCliente.addItem("UF")
        self.estadoCliente.addItem("AC")
        self.estadoCliente.addItem("AL")
        self.estadoCliente.addItem("AM")
        self.estadoCliente.addItem("AP")
        self.estadoCliente.addItem("BA")
        self.estadoCliente.addItem("CE")
        self.estadoCliente.addItem("DF")
        self.estadoCliente.addItem("ES")
        self.estadoCliente.addItem("GO")
        self.estadoCliente.addItem("MA")
        self.estadoCliente.addItem("MG")
        self.estadoCliente.addItem("MS")
        self.estadoCliente.addItem("MT")
        self.estadoCliente.addItem("PA")
        self.estadoCliente.addItem("PB")
        self.estadoCliente.addItem("PE")
        self.estadoCliente.addItem("PI")
        self.estadoCliente.addItem("PR")
        self.estadoCliente.addItem("RJ")
        self.estadoCliente.addItem("RN")
        self.estadoCliente.addItem("RO")
        self.estadoCliente.addItem("RR")
        self.estadoCliente.addItem("RS")
        self.estadoCliente.addItem("SC")
        self.estadoCliente.addItem("SE")
        self.estadoCliente.addItem("SP")
        self.estadoCliente.addItem("TO")

        #Tipo de Atendiemnto
        self.ComboAtendimento.addItem("Particular")
        self.ComboAtendimento.addItem("Convênio")


        if self.ComboAtendimento == "Convênio":
            self.NomeConvenio.setEnabled(False)



        #Especialista

        self.Especialista.addItem("Cardiologia")
        self.Especialista.addItem("Cardiologia Pediatrica")
        self.Especialista.addItem("Dermatovenereologia")
        self.Especialista.addItem("Doenças Infercciosas")
        self.Especialista.addItem("Endocrionologia")
        self.Especialista.addItem("Ginecologia")
        self.Especialista.addItem("Ginecologia/Obstetrica")
        self.Especialista.addItem("Imunoalergologia")
        self.Especialista.addItem("Hematologia")
        self.Especialista.addItem("Medico Geral")
        self.Especialista.addItem("Neurologia")
        self.Especialista.addItem("Oncologia")
        self.Especialista.addItem("Otorrinolaringologia")
        self.Especialista.addItem("Patologia")
        self.Especialista.addItem("Pediatria")
        self.Especialista.addItem("Pneumologia")
        self.Especialista.addItem("Psiquiatria")
        self.Especialista.addItem("Radiologia")
        self.Especialista.addItem("Urulogia")

        #Forma de Atendimento
        self.FormAtendimento.addItem("Normal")
        self.FormAtendimento.addItem("Urgência")

        #Combo de convenios
        self.NomeConvenio.addItem("")
        self.NomeConvenio.addItem("Amil")
        self.NomeConvenio.addItem("Bradesco")
        self.NomeConvenio.addItem("Medservice")
        self.NomeConvenio.addItem("Omint")
        self.NomeConvenio.addItem("Assefaz")
        self.NomeConvenio.addItem("GAMA")



    def Clear(self):
        self.CamNomeCompleto.clear()
        self.dtaNascimento.clear()
        self.IdadeCliente.clear()
        self.CPFCliente.clear()
        self.RGCliente.clear()
        self.CampEmail.clear()
        self.PassaporteCliente.clear()
        self.CampCelular.clear()
        self.CEPCliente.clear()
        self.ENDClinete.clear()
        self.NumeroCasa.clear()
        self.BairroCliente.clear()
        self.CompCliente.clear()
        self.OBSCliente.clear()

    def Salvar(self):
        nome = ""
        data = ""
        idade = ""
        cpf = ""
        rg = ""
        uf = -1
        email = ""
        passaport = ""
        menor = ""
        celular = ""
        cep = ""
        end =""
        numeroCasa =""
        bairro = ""
        cidade = ""
        uf1 = -1
        TAtendimento = -1
        NConvenio = -1
        hora = ""
        especialista = -1
        FAtendimento = -1
        valor = ""
        obsCliente = ""

        nome = self.CamNomeCompleto.text()
        data = self.dtaNascimento.text()
        idade = self.IdadeCliente.text()
        cpf = self.CPFCliente.text()
        rg = self.RGCliente.text()
        uf = self.UFExpedicao.itemText(self.UFExpedicao.currentIndex())
        email = self.CampEmail.text()
        passaport = self.PassaporteCliente.text()
        celular = self.CampCelular.text()
        cep = self.CEPCliente.text()
        end = self.ENDClinete.text()
        numeroCasa = self.NumeroCasa.text()
        bairro = self.BairroCliente.text()
        cidade = self.CompCliente.text()
        uf1 = self.estadoCliente.itemText(self.estadoCliente.currentIndex())
        TAtendimento = self.ComboAtendimento.itemText(self.ComboAtendimento.currentIndex())
        NConvenio = self.NomeConvenio.itemText(self.NomeConvenio.currentIndex())
        hora = self.hrEntrada.text()
        especialista = self.Especialista.itemText(self.Especialista.currentIndex())
        FAtendimento = self.FormAtendimento.itemText(self.FormAtendimento.currentIndex())
        valor = self.ValorAtendimento.text()
        obsCliente = self.OBSCliente.toPlainText()

        try:
            self.conn = sqlite3.connect("Paciente.db")
            self.c = self.conn.cursor()
            self.c.execute("INSERT INTO paciente (nome, data, idade, cpf, rg, uf, email, passaport, celular, cep, end, numeroCasa, bairro, cidade, uf1, TAtendimento, NConvenio, hora, especialista, FAtendimento, valor, obsCliente) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                           (nome, data, idade, cpf, rg, uf, email, passaport, celular, cep, end, numeroCasa, bairro, cidade, uf1, TAtendimento, NConvenio, hora, especialista, especialista, valor, obsCliente))
            self.conn.commit()
            self.c.close()
            self.conn.close()
            QMessageBox.information(QMessageBox(), 'Salvo com sucesso', 'Paciente salvo com sucesso')
        except Exception:
            QMessageBox.warning(QMessageBox(), 'Erro ao salvar', 'Confira todos os campos')






    #def Data(self):
    #    endereco = pycep_correios.consultar_cep('73340105')
    #   self.CEPCliente.setText(endereco.get(''))
    #   self.ENDClinete.setText(endereco['end'])
    #  self.BairroCliente.setText(endereco['bairro'])
    #  self.CompCliente.setText(endereco['cidade'])"""










    def retranslateUi(self, TelaAtendimento):
        _translate = QtCore.QCoreApplication.translate
        TelaAtendimento.setWindowTitle(_translate("TelaAtendimento", "Atendimento Cliente"))
        self.label_19.setText(_translate("TelaAtendimento", "Observação do Cliente:"))
        self.label_9.setText(_translate("TelaAtendimento", "Bairro:"))
        self.label_15.setText(_translate("TelaAtendimento", "Hora:"))
        self.label.setText(_translate("TelaAtendimento", "RG:"))
        self.label_3.setText(_translate("TelaAtendimento", "Passaporte:"))
        self.label_11.setText(_translate("TelaAtendimento", "Cidade:"))
        self.lblNomeCompleto.setText(_translate("TelaAtendimento", "Nome Completo:"))
        self.label_16.setText(_translate("TelaAtendimento", "Especialista:"))
        self.label_13.setText(_translate("TelaAtendimento", "Tipo de Atendimento:"))
        self.CPFProprio.setText(_translate("TelaAtendimento", "Proprio"))
        self.lblNascimento.setText(_translate("TelaAtendimento", "Nascimento:"))
        self.RGProprio.setText(_translate("TelaAtendimento", "Proprio"))
        self.label_17.setText(_translate("TelaAtendimento", "Forma de Atendimento:"))
        self.label_4.setText(_translate("TelaAtendimento", "Dados do Cleinte"))
        self.groupBox_2.setTitle(_translate("TelaAtendimento", "Menor?"))
        self.radioButton_2.setText(_translate("TelaAtendimento", "Não"))
        self.radioButton.setText(_translate("TelaAtendimento", "Sim"))
        self.label_10.setText(_translate("TelaAtendimento", "Estado:"))
        self.label_7.setText(_translate("TelaAtendimento", "Endereço:"))
        self.label_8.setText(_translate("TelaAtendimento", "N°:"))
        self.lblIdade.setText(_translate("TelaAtendimento", "Idade:"))
        self.label_5.setText(_translate("TelaAtendimento", "Endereço do Cliente"))
        self.label_6.setText(_translate("TelaAtendimento", "CEP:"))
        self.label_12.setText(_translate("TelaAtendimento", "Tipo de Atendimento"))
        self.label_18.setText(_translate("TelaAtendimento", "Valor:"))
        self.lblCPF.setText(_translate("TelaAtendimento", "CPF:"))
        self.label_2.setText(_translate("TelaAtendimento", "UF:"))
        self.label_14.setText(_translate("TelaAtendimento", "Nome do convênio:"))
        self.groupBox.setTitle(_translate("TelaAtendimento", "Contatos"))
        self.label_20.setText(_translate("TelaAtendimento", "Email:"))
        self.label_21.setText(_translate("TelaAtendimento", "Celular:"))
        self.btnCancelar.setText(_translate("TelaAtendimento", "Cancelar"))
        self.btnLimpar.setText(_translate("TelaAtendimento", "Limpar"))
        self.btnSalvar.setText(_translate("TelaAtendimento", "Salvar"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaAtendimento = QtWidgets.QDialog()
    ui = Ui_TelaAtendimento()
    ui.setupUi(TelaAtendimento)
    TelaAtendimento.show()
    sys.exit(app.exec_())